set_property SRC_FILE_INFO {cfile:D:/projects/github/mrunmoy/fpga/blinky/blinky.srcs/constrs_1/new/consts.xdc rfile:../../../blinky.srcs/constrs_1/new/consts.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U16  IOSTANDARD LVCMOS33 } [get_ports led]
