webtalk_init -webtalk_dir D:\\projects\\github\\mrunmoy\\fpga\\led_pmod\\led_pmod.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-14 22:05:02" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4q8184hn9qv4lqdl7e8cfo035s" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.136 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1547462160664" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1547462160664"
webtalk_add_data -client sdk -key uid -value "1547462315894" -context "sdk\\\\bsp/1547462315894"
webtalk_add_data -client sdk -key hwid -value "1547462160664" -context "sdk\\\\bsp/1547462315894"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1547462315894"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1547462315894"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1547462315894"
webtalk_add_data -client sdk -key uid -value "1547462318423" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key hwid -value "1547462160664" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key bspid -value "1547462315894" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key projSize -value "86.97265625" -context "sdk\\\\application/1547462318423"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1547463902607"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1547463902607"
webtalk_transmit -clientid 171625142 -regid "" -xml D:\\projects\\github\\mrunmoy\\fpga\\led_pmod\\led_pmod.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\projects\\github\\mrunmoy\\fpga\\led_pmod\\led_pmod.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\projects\\github\\mrunmoy\\fpga\\led_pmod\\led_pmod.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
